version: "2.1"

services:
  pa11y:
    hostname: pa11y
    image: drydockcloud/ca-pa11y:0.1
    command: tail -f /dev/null
    volumes:
      - ../tests/pa11y/wcag2-config.json:/home/node/app/wcag2-config.json

  solr:
    image: docksal/solr:4.x
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr

  cli:
    environment:
      - IS_DOCKSAL_PROJECT 
      - DRUPAL_HASH_SALT
      # Git repo for the host that will be pushed to with "fin deploy"
      - REMOTE_GIT_REPO
      # Git branch that will be pushed to when DEV_BRANCH updates.
      - REMOTE_DEPLOY_BRANCH
      # "pantheon" or "acquia"
      - HOSTING_PLATFORM
      # Necessary for pantheon. The machine name of the account.
      - HOSTING_SITE
      # Determines which environment "fin pull db/files" grabs from.
      - HOSTING_ENV
      # Name of the remote to push DEV_BRANCH updates to.
      - DEV_BRANCH       
      # Name of the theme, for Emulsify only.
      - THEME_NAME
      # Used for Drupal site uuid.
      - UUID
      - COMPOSER_DEFAULT_VERSION
      - STORYBOOK_FOLDER
      - TRAVIS_REPO_SLUG
      - GH_TOKEN
