<?php

/**
 * @file
 * Contains countyoc_layouts.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function countyoc_layouts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the countyoc_layouts module.
    case 'help.page.countyoc_layouts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom layouts for layout builder.') . '</p>';
      return $output;

    default:
  }
}
