#!/usr/bin/env bash

## Test behat
##
## Usage: fin behat 

# Abort if anything fails
set -e

# Debug mode switch
if [[ "${DEBUG}" != "" ]]; then
    set -x
fi

fin exec ./vendor/bin/behat -c ./tests/behat/behat.yml
