#!/usr/bin/env bash

## Updates Drupal8 Core when in TravisCI cron or local
## Usage: fin d8-coreupdate
## Parameters: N/A
## Dependency Environment Variable:
## fin config set --global LOCAL_D8CORE_UPDATE=true
 
if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]] || [[ "${LOCAL_D8CORE_UPDATE}" = "true" ]]; then
  echo "PLACEHOLDER: Triggered via cron. Can run 'fin d8-coreupdate'."
else
  echo "PLACEHOLDER: Not run from travis cron. 'fin d8-coreupdate' NOT allowed."
fi
