#!/usr/bin/env bash

if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then
  echo "PLACEHOLDER: Triggered via cron. Can run 'fin d8-coreupdate'."
else
  echo "PLACEHOLDER: Not run from travis cron. 'fin d8-coreupdate' NOT allowed."
fi
