#!/usr/bin/env bash

## Updates Drupal Core when in TravisCI cron or from local.
## Usage: fin drupal-coreupdate [try|sendpr] [--local]
## Parameters:
## try|sendpr  Either try doing core update(default) or send PR
## --local     Run from local environment.

coreupdate_try() {
  if [[ $(fin composer outdated "drupal/*"|grep -ic "^drupal/core") -eq 1 ]]; then
     fin composer update drupal/core --with-dependencies && \
     fin drush updb -y                                   && \
     fin drush cr -y                                     && \
     fin drush st
  else
     echo "No drupal core update detected."
  fi
}

prep_drupalcoreupdate_branch() {
  cd ../
  git clone https://${GH_TOKEN}@github.com/promet/provus.git $DRUPALCORE_BRANCH
  cd $DRUPALCORE_BRANCH
  git fetch
  git checkout -b $DRUPALCORE_BRANCH
  cp ../provus/composer.lock .
  git add composer.lock
  git commit -m"PTECH-1569: Drupal update to ${dcore_ver}"
  git push -u origin $DRUPALCORE_BRANCH
  cd ../provus
}

coreupdate_pr() {
  pwd
  git branch
  git remote -v
  dcore_ver=$(fin drush st|grep "Drupal version"|cut -d':' -f2|sed 's/\ //g'|sed 's/\r//g')
  DRUPALCORE_BRANCH=drupalcore_${dcore_ver}

  git fetch
  PRBRANCH_EXIST=$(git ls-remote https://${GH_TOKEN}@github.com/promet/provus.git | grep -c ${DRUPALCORE_BRANCH}$)

  ## Prep PR source branch
  if [[ $PRBRANCH_EXIST -eq 0 ]]; then
     prep_drupalcoreupdate_branch
  else
     echo "[INFO] ${DRUPALCORE_BRANCH} already exist in remote repo."
  fi

set -xv
  echo "[INFO] Creating PR now."
  curl -X POST -u "icasimpan:${GH_TOKEN}"                          \
       -H "Accept: application/vnd.github.v3+json"                 \
       https://api.github.com/repos/promet/provus/pulls            \
       -d '{"title":"Drupal core 8.9.5","head":"drupalcore_8.9.5","base":"develop"}'
set +xv
       -d '{"title":"Drupal core $dcore_ver","head":"${DRUPALCORE_BRANCH}","base":"develop"}'
}

if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]] || [[ "$2" = "--local" ]]; then
  case $1 in
    try)
      coreupdate_try
    ;;
    sendpr)
      coreupdate_pr
    ;;
    *)
      coreupdate_try
    ;;
  esac
else
  echo "Drupal core update skipped. See 'fin help drupal-coreupdate'."
fi
