#!/usr/bin/env bash

#: exec_target = cli

## Updates Drupal Core when in TravisCI cron or from local.
## Usage: fin drupal-coreupdate [try|sendpr] [--local]
## Parameters:
## try|sendpr  Either try doing core update(default) or send PR
## --local     Run from local environment.

${PROJECT_ROOT}/scripts/bin/drupal-coreupdate.sh $*
