#!/usr/bin/env bash

## Initialize/reinstall site
##
## Usage: fin init-site

fin composer install -vvv
fin drush si -y --account-pass=admin
fin drush config-set system.site uuid ${UUID} -y
fin drush entity:delete shortcut_set
fin drush cim -y
fin build-theme
fin test-content
fin drush pmu shortcut
fin drush en -y shortcut
