#!/usr/bin/env bash

## Runs PHPUnit tests found in custom code
##
## Usage: fin phpunit <args>
##
## Run `fin phpunit -h` for a full list of options.
##
## Runs with settings in the root `phpunit.xml` file.

fin exec ${HTML_ROOT}/scripts/bin/phpunit.sh 
