#!/usr/bin/env bash

## Deploy storybook to the oc-design.prometdev.com site. 
##
## Usage: fin init

git reset --hard origin/storybook
echo "Copying storybook"
fin exec "cp -r web/themes/custom/countyoc .; cd countyoc; yarn"
git checkout storybook
git pull
echo "Building storybook"
#fin exec "cd countyoc; yarn build-storybook -o ../storybook"
echo "Removing artifact"
#fin exec "rm -rf countyoc"
echo "Adding to git"
git add storybook
git commit -m "Updates storybook"
#git push origin storybook
